### ISSUE TITLE
 hello 

### ISSUE THREAD

**Issue by 4puwen** [Wellbek/WellOrbwalker#1]
hello how can i change to activate key?

**Comment by Wellbek** [comment]
As it is explained in the README, you can change your activation key to whatever key you like by editing the "settings.json" file in the settings folder that is generated inside the directory you installed the program in:

1. Locate your installation folder, run the .exe if you haven't already, and close it. After, the folder in the image should appear. Open the folder.
![image](https://user-images.githubusercontent.com/54329793/231556951-c5b344bc-e5b1-40db-8052-95f5a88fc622.png)

2. Edit the .json file with any text-editor. 
![image](https://user-images.githubusercontent.com/54329793/231557217-b4fbeca3-ee96-481a-aa98-74486a344f81.png)

3. Scroll all the way down and change the number in {"ActivationKey:[YOUR NUMBER]"} to the number corresponding to your desired key. 
![image](https://user-images.githubusercontent.com/54329793/231557328-99950c78-6f34-4f10-ba61-288f9c3c018b.png)

4. Save and start the .exe again. It should now work with your new keybinding.
